### ISSUE TITLE
GWT SDK 2.8 support?

### ISSUE THREAD

**Issue by doggie1989** [WeTheInternet/xapi#7]

**Comment by doggie1989** [comment]
@JamesXNelson 

I saw gwt 2.8.0 beta released
Is xapi easy to update?

**Comment by JamesXNelson** [comment]
I will be rebasing on top of 2.8 soon, but my fork has some extra things that GWT vanilla does not.

It should be a trivial update, but I will not release anything to maven central until after gwt 2.8 final is public.

**Comment by doggie1989** [comment]
@JamesXNelson 
Long time no see.

I have heavily used xapi's gwt reflection in several projects(production).

what is the extra things your fork has?

**Comment by JamesXNelson** [comment]
Heya.

The primary extra thing is the magic method injection which is used to dynamically replace any method call with new ast objects (generally pointing to generated code), along with a bunch of extra JRE emulation that was missing from Gwt core.

For the next version, I am trying to move away from performing magic method injection in the Gwt compiler, and am instead doing it via javac plugns.  This means that I may not have to maintain a fork of Gwt in order to be able to provide reflection and other forms of magic.  The new system is doing source-level replacement, so instead of creating an AST JMethodCall and inserting it at Gwt compile time, I would instead produce an alternative source file with that source node actually changed.

This will mean that after you run javac, it will produce the same source that would normally be produced at Gwt compile time, except you can actually see that source code (and debug into it).  

In addition to this, I've also extended the java language with a templating syntax, to create cross-platform UIs that can bind simply to standard java files.  It looks something like this:

    @Ui(`<box title = $this::getTitle
                      style = .className { width: $this.getWidth() }
                      data = { one: 1, two: 1 + 1.0 }
                      onClick=()->Window.alert("You clicked " + $this.getTitle())
             ><div ref="child" />
            </box>
    `)
     public interface MyElement extends UiElement {
         String getTitle();
         int getWidth();
         DivElement getChild();
     }


The actual syntax of the language compilation is done, and I'm currently working on the cross-platform UI generator aspect; the prototype is actually in javafx instead of Gwt, as I can iterate on it faster, and I want to make the UI a program that will watch the filesystem and invoke the generator whenever sources change (to avoid relying on any IDE / build system).

I do have some very limited support for using the templating language in Gwt, via my generated web component library; it will insert the resolved templates into the shadow dom, and do some preliminary binding to css, but I wanted to avoid making the core library depend on web-only features, so I'm putting that particular prototype on pause until the javafx version is usable (hello world app with lambdas, method references and { json: "objects" } is done.

So!

Depending on when / if I get time to port the reflection library over to the new javac plugin system, I may or may not do a Gwt 2.8 release of the fork.  Given that you are actually using it, I will take that into consideration, and attempt to do a rebase and release of latest 2.8; I've fallen behind trunk for quite a while now as I was waiting until 2.8 was finalized before biting the bullet; they last rebase they were in the middle of some incremental compiler changes that cost me three weeks and lots of sanity to recover from, so I'm going to wait until all the dust has settled before allocating time to it again.


Many of my own creations also rely on the magic method injection support that reflection support is based on, so do not worry, I will not be letting any of the features die; I just may be supporting them in new (more efficient / sane) ways.  The biggest reason to move to javac instead of gwtc is that gwtc will perform much, much faster if I just feed it raw source instead of try to do anything dynamic at compile time.  If you look at the class, MinimalRebuildCache, you will likely see why...  ....They track every method and type to every other method and type accessing it, and they have to update it with special mappings for usages of GWT.create...  ....which I had to hack into to also include magic method injection (which is capable of inserting any amount of AST, and not just a constructor to a generated type).

So!  

If you are interested in leveraging magic method injection for any code generators you may be interested in, let me know, and I can be sure to point you in a direction that works right now, and will continue to work in the future (hint: generate as much as you can in new files, so you only have to inject a single method call).

Let me know if you'd like to chat more in person in case I've missed anything you are interested in.

**Comment by JamesXNelson** [comment]
Reading the thread again, I should mention the "extra things" are primarily the MinialRebuildCache support.  I heard they are also having issues with default interface methods, which is also something I've changed quite a bit (so I can use them in JSNI)... So, those are the primary blockers for me that make me hesitant to rebase more times than is necessary.

**Comment by JamesXNelson** [comment]
If there are any particular features in latest Gwt that you are missing, let me know, and I can prioritize them in a release.  I am going to be releasing a new version of my framework once this templating language is complete, and will likely need to do either a Gwt 2.8, 2.7.1 or 2.8-rc1 to go along with the other changes I've made in the last year or so. :-) 

If you have any pressing needs, lemme know and I can either address that by doing a 2.7.1 against my older version, or wait until I rebase and do 2.8.X.

**Comment by doggie1989** [comment]
task devmode (dependsOn: classes, type: JavaExec) {

	description = "Run development mode"

	main = 'com.google.gwt.dev.DevMode'

	classpath {
		[
			sourceSets.main.java.srcDirs,
			// Java source
			sourceSets.main.output.classesDir,
			// Generated classes
			sourceSets.main.compileClasspath,
			configurations.compile
		]}

	args = (gwtModule instanceof List)?gwtModule:[gwtModule]
	args += [
		'-noincremental',
		'-startupUrl',
		"http://${gwtServerHost}:${gwtServerPort}/${gwtStartupUrl}",
		'-war',
		gwtWarPath
	]

	maxHeapSize = '2048M'
}

this is my gradle task...
I must add -noincremental to args,otherwise will case some odd bug
